name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        timeout-minutes: 5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        timeout-minutes: 5

      - name: Install dependencies
        run: |
          n=0
          until [ $n -ge 3 ]
          do
            npm ci && break
            n=$((n+1))
            echo "Retry attempt $n..."
            sleep 15
          done
        timeout-minutes: 10

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
        timeout-minutes: 15

      - name: Verify build output
        run: |
          if [ ! -d "dist/online-c-store/browser" ]; then
            echo "Error: Build directory not found"
            exit 1
          fi
          echo "Build directory contents:"
          ls -la dist/online-c-store/browser

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
        env:
          DEBUG: 'true'
        timeout-minutes: 10
